### ISSUE TITLE
Enforce permission

### ISSUE THREAD

**Issue by Vgratioulet** [adixon/ca.civicrm.contributextra#3]
The contribution page button appears on every contact for every user, I would rather have it only if some permission is met, like 'CiviContribute: edit contributions'

**Comment by adixon** [comment]
This extension doesn't handle the permissions to use the link it creates, those are from CiviCRM core. I think the current setup is appropriate for most sites - for example, if you have a collection of people using your site to solicit donations, you generally want them to be able to create such contributions but not edit them.

**Comment by Vgratioulet** [comment]
For a user that doesn't have 'CiviContribute: edit contributions' or even 'CiviContribute: access contributions', I find it odd to have the contribution page button on top of the contacts.

**Comment by adixon** [comment]
Maybe odd, but definitely useful - e.g. my previous use-case (such as for phone banking - you may not want to give out detailed contribution history, but still ask them to take donation information over the phone).
